server:
  servlet:
    context-path:/api
#
#logging:
#  level:
#    br:
#      com:
#        letscode:
#          bookstore:
#            BookService: debug

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./starwarsdb;MODE=MYSQL;AUTO_SERVER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS STARWARS
    username: user
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: STARWARS
        format_sql: true
  h2:
    console:
      settings:
        web-allow-others: true
      enable: true
      path: /h2-console